name: build
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup ndk
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
          local-cache: true
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: script run line haha
        run: |
          haxe -version
          haxelib install lime 7.9.0
          haxelib git openfl https://github.com/openfl/openfl develop
          haxelib install flixel 4.11.0
          haxelib git hxcpp https://github.com/haxefoundation/hxcpp master
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.11.0
          haxelib install hscript
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/Sirox228/extension-webm
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib install actuate
          haxelib list
      - name: compile mobile
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: compile
        run: |
          haxelib run lime rebuild hxcpp
          haxelib run lime build android
      - name: download build
        uses: actions/upload-artifact@main
        with:
          name: kfp
          path: export/release/android/bin/app/build/outputs/apk/debug
